version: '3.8'

networks:
  frontend:
  backend:

volumes:
  vendor-prod:
  db-data-prod:

services:
  web:
    image: nginx:1.21-alpine
    container_name: web
    ports:
      - 80:80
    volumes:
      - ./logs/web:/var/log/nginx
      - ./docker/prod/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./webroot:/var/www/html
    networks:
      - frontend
      - backend
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: ./docker/prod/php-fpm/Dockerfile
    container_name: app
    volumes:
      - ./:/var/www/html
      - vendor-prod:/var/www/html/Vendor
    networks:
      - backend
    depends_on:
      - db
  front:
    build:
      context: .
      dockerfile: ./docker/prod/node/Dockerfile
    container_name: front
    environment:
      - NODE_ENV=production
  db:
    image: mysql:8.0
    container_name: db
    ports:
      - 3306:3306
    # パスワードで mysql にログインできるようにする
    command: --authentication_policy=mysql_native_password
    # mbind: Operation not permitted が mysql エラーログに表示されないようにする対策
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_DATABASE=study_cakephp2
      - MYSQL_USER=default
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
      # タイムゾーンを 東京 にする
      - TZ=Asia/Tokyo
    volumes:
      - ./logs/db:/var/log/mysql
      - ./docker/prod/mysql/init:/docker-entrypoint-initdb.d
      - ./docker/prod/mysql/etc-mysql.cnf:/etc/mysql/conf.d/etc-mysql.cnf
      - db-data-prod:/var/lib/mysql
    networks:
      - backend
