SET NAMES utf8mb4;

INSERT IGNORE INTO `users` VALUES
(UUID(), 'admin', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'admin', 'システム管理者', NOW(), NOW()),
(UUID(), 'author1', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'author', 'ユーザー1', NOW(), NOW()),
(UUID(), 'author2', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'author', 'ユーザー2', NOW(), NOW()),
(UUID(), 'author3', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'author', 'ユーザー3', NOW(), NOW()),
(UUID(), 'author4', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'author', 'ユーザー4', NOW(), NOW()),
(UUID(), 'author5', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'author', 'ユーザー5', NOW(), NOW()),
(UUID(), 'author6', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'author', 'ユーザー6', NOW(), NOW()),
(UUID(), 'author7', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'author', 'ユーザー7', NOW(), NOW()),
(UUID(), 'author8', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'author', 'ユーザー8', NOW(), NOW()),
(UUID(), 'author9', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'author', 'ユーザー9', NOW(), NOW()),
(UUID(), 'author10', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'author', 'ユーザー10', NOW(), NOW()),
(UUID(), 'author11', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'author', 'ユーザー11', NOW(), NOW()),
(UUID(), 'author12', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'author', 'ユーザー12', NOW(), NOW()),
(UUID(), 'author13', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'author', 'ユーザー13', NOW(), NOW()),
(UUID(), 'author14', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'author', 'ユーザー14', NOW(), NOW()),
(UUID(), 'author15', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'author', 'ユーザー15', NOW(), NOW()),
(UUID(), 'author16', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'author', 'ユーザー16', NOW(), NOW()),
(UUID(), 'author17', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'author', 'ユーザー17', NOW(), NOW()),
(UUID(), 'author18', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'author', 'ユーザー18', NOW(), NOW()),
(UUID(), 'author19', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'author', 'ユーザー19', NOW(), NOW()),
(UUID(), 'author20', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'author', 'ユーザー20', NOW(), NOW()),
(UUID(), 'author21', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'author', 'ユーザー21', NOW(), NOW()),
(UUID(), 'author22', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'author', 'ユーザー22', NOW(), NOW()),
(UUID(), 'author23', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'author', 'ユーザー23', NOW(), NOW()),
(UUID(), 'author24', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'author', 'ユーザー24', NOW(), NOW()),
(UUID(), 'author25', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'author', 'ユーザー25', NOW(), NOW()),
(UUID(), 'author26', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'author', 'ユーザー26', NOW(), NOW()),
(UUID(), 'author27', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'author', 'ユーザー27', NOW(), NOW()),
(UUID(), 'author28', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'author', 'ユーザー28', NOW(), NOW()),
(UUID(), 'author29', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'author', 'ユーザー29', NOW(), NOW())
;
